T009 nav desktop
YTech-NZ/website_frontend pull request #13
Opened 2022-03-14 17:58 UTC by AwesomeJackify

2022-04-24 23:24 UTC, KennethZhu904 requested changes
Overall, great effort on this ticket.  Just a couple of comments that I have made in this PR. Please make sure to make the changes before tonight's meeting.

2022-04-24 23:24 UTC, KennethZhu904 commented on src/components/Navbar.tsx
> +					</a> */}
remove those comments if you are not using this code anymore

2022-04-24 23:24 UTC, KennethZhu904 commented on src/screens/Landing.tsx
remove that space

2022-04-24 23:24 UTC, KennethZhu904 commented on src/styles/navbar.scss
> +
remove those comments if you are not using it

2022-04-24 23:24 UTC, KennethZhu904 commented on src/widgets/Image.tsx
> +
remove that space

2022-04-24 23:24 UTC, KennethZhu904 commented on src/components/Navbar.tsx
> +import { SocialIcon } from 'react-social-icons';
remove any unnecessary imports, especially SocialIcon. SocialIcon is not being used in this code.

2022-04-25 01:07 UTC, KennethZhu904 approved these changes
LGTM!

2022-04-25 08:07 UTC, johnchen383 requested changes
Remove package-lock.json please

2022-07-17 07:28 UTC, johnchen383 approved these changes
Some refactoring could be done to clean the codebase but I think this should be fine for now. LGTM if ur fine with the edits I've made.

2022-07-17 09:26 UTC, merged