T012 Firebase
YTech-NZ/website_frontend pull request #35
Opened 2022-07-17 10:52 UTC by MaxDangVu136

Issue: Needed to put Max's google signup implementation in a separate folder from working Firebase code. 

Solution: Added files to folder 'google_signup_unfinished' for potential use later, also commented briefly on what each file does. 

Risk: Minimal

2022-07-17 11:26 UTC, KennethZhu904 approved these changes
LGTM. In the future, if you are making notes to remind yourself what the code does, please make sure to remove them . I suggest you put a word that prompt you to remove your comment once you finish the task. Some comments in your code are not neccessary. E.g. line 17 and 20 of Admin.tsx file as it is understandable from developers point of view.

2022-07-17 11:26 UTC, KennethZhu904 commented on src/components/Authentication/SignIn.tsx
> +
remove that space

2022-07-17 23:16 UTC, johnchen383 requested changes
Could we add Admin.tsx to the screens folder. Also, nitpicking but can we change Authentication to lowercase for consistency. Also FirebaseConfig.

2022-07-17 23:48 UTC, johnchen383 requested changes
Can we delete package-lock.json? And ensure a rebuild with `yarn install` then `yarn start`. Sorry shouldve spotted that first time round.

2022-07-18 00:02 UTC, johnchen383 approved these changes
LGTM. Feel free to merge and move ur notion ticket

2022-07-18 00:32 UTC, merged