T004 media insertion
YTech-NZ/website_frontend pull request #8
Opened 2022-02-24 23:48 UTC by MaxDangVu136

Issue: no video implemented. 
Solution: implemented YouTube video feature (minimal viable solution). 
Risk: may override some of Kenneth's previous implementation.

2022-02-24 23:52 UTC, johnchen383 requested changes
Please remove .vscode from being pushed to remote repo - it doesn't need to be there.

Alos, node-sass was removed as a package. This needs to be there.

Remove video-react if not using it.

Not too sure why tsconfig changed. Please advise if its needed. Else, react-jsx should be the proper field.

2022-02-24 23:53 UTC, johnchen383 commented
Also, please try to remove package-lock.json... im assuming a npm command was used at some point but we dont want duplicate files

2022-02-24 23:54 UTC, johnchen383 commented
In general, try to make your components widgets first and then we can merge to main. Good work though!

2022-02-27 19:25 UTC, johnchen383 requested changes

2022-02-27 19:25 UTC, johnchen383 commented on package.json
> +    "react-video": "^1.5.3",
remove dependency

2022-02-27 19:25 UTC, johnchen383 commented on package.json
> +  },
remove dependency

2022-02-27 19:25 UTC, johnchen383 commented on src/styles/styles.scss
> +.video-responsive {
try for a better name than `styles.scss`. How does this differ from youtubevideo.scss

2022-02-27 19:25 UTC, johnchen383 commented on src/styles/youtube_video.scss
> +.cust_video {
remove underscore for consistent naming.. we use camelcase for styles

2022-02-27 19:25 UTC, johnchen383 commented on src/widgets/YouTubeVideo.tsx
> +// Source code: https://dev.to/bravemaster619/simplest-way-to-embed-a-youtube-video-in-your-react-app-3bk2
If poss, would remove capitalisation of T

2022-02-27 19:26 UTC, johnchen383 commented on package.json
> +  },
dev sass dependecy to clarify

2022-02-27 19:26 UTC, johnchen383 commented on package.json
> +    "react-video": "^1.5.3",
react-video

2022-02-27 19:29 UTC, johnchen383 requested changes
As commented

2022-03-04 02:20 UTC, johnchen383 requested changes
Just change the naming conventions and then I'll run and give it a go. But looking good!

2022-03-04 02:20 UTC, johnchen383 commented on src/styles/youtube-video.scss
> +.video-responsive {
please use camelCase for .scss files

2022-03-04 02:20 UTC, johnchen383 commented on src/widgets/Youtube-Video.tsx
> +import "../styles/youtube-video.scss";
please use PascalCase for .tsx files

2022-03-14 07:15 UTC, johnchen383 requested changes
As commented

2022-03-14 07:15 UTC, johnchen383 commented on public/index.html
> +  <link rel="stylesheet" href="https://video-react.github.io/assets/video-react.css"/>
Remove import plz

2022-03-14 09:41 UTC, KennethZhu904 approved these changes
LGTM after changes requested by John! :)

2022-03-15 02:15 UTC, johnchen383 approved these changes
LGTM. Thanks for all the hard work!

2022-03-15 02:45 UTC, merged